import { Dimensions } from "react-native";
export const height = Dimensions.get("window").height;
export const width = Dimensions.get("window").width;
// export const primaryColor = "#256FEF";
export const primaryColor = "#FF4B3A";
// export const secondaryColor = "#77a6f7";
export const secondaryColor = "#FF9551";
export const orange = "#ed8449";
export const brown = "#FF9551";
export const green = "#3ab757";
export const red = "crimson";
